//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookMaster1.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.BookCover = new HashSet<BookCover>();
            this.BookSubject = new HashSet<BookSubject>();
            this.Circulation = new HashSet<Circulation>();
            this.Cover = new HashSet<Cover>();
            this.BookAuthors = new HashSet<BookAuthors>();
        }
    
        public string Id { get; set; }
        public string Title { get; set; }
        public string Subtitle { get; set; }
        public System.DateTime FirstPublishDate { get; set; }
        public string Description { get; set; }

        public string Authors
        {
            get
            {
                return "by " +string.Join(" ,", BookAuthors.Select(bookAuthor=>bookAuthor.Author.FullName));
            }
        }
        public string AuthorsList
        {
            get
            {
                return string.Join(",", BookAuthors.Select(bookAuthor => bookAuthor.Author.FullName));
            }
        }

        public string Subjects
        {
            get
            {
                return string.Join(",", BookSubject.Select(bookSubject => bookSubject.Subject.Name));
            }
        }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookCover> BookCover { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookSubject> BookSubject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Circulation> Circulation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cover> Cover { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookAuthors> BookAuthors { get; set; }
    }
}
