//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookMaster1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Circulation
    {
        public int Id { get; set; }
        public System.DateTime DateOfIssue { get; set; }
        public Nullable<System.DateTime> DateOfReturn { get; set; }
        public System.DateTime ReturnUntil { get; set; }
        public string CustomerId { get; set; }
        public string BookId { get; set; }
        public int EmploeeId { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
