//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookMaster1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Circulation = new HashSet<Circulation>();
        }
    
        public string Id { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public string MiddleName { get; set; }
        public string Zip { get; set; }
        public string Addres { get; set; }
        public string PhoneNubmer { get; set; }
        public string Email { get; set; }
        public int CityId { get; set; }
        public string FullName
        {
            get
            {
                return $"{Lname} {Fname} {MiddleName}";
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Circulation> Circulation { get; set; }
        public virtual City City { get; set; }
    }
}
