//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookMaster1.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BookMasterEntities2 : DbContext
    {
        public BookMasterEntities2()
            : base("name=BookMasterEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Author> Author { get; set; }
        public virtual DbSet<Book> Book { get; set; }
        public virtual DbSet<BookCover> BookCover { get; set; }
        public virtual DbSet<BookSubject> BookSubject { get; set; }
        public virtual DbSet<Circulation> Circulation { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Cover> Cover { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<Subject> Subject { get; set; }
        public virtual DbSet<BookAuthors> BookAuthors { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
    }
}
